services:
  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: app
    ports:
      - 5433:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data

  minio:
    image: minio/minio
    container_name: minio
    restart: always
    environment:
      MINIO_ACCESS_KEY: admin
      MINIO_SECRET_KEY: minioadmin
    ports:
      - 9000:9000
    command: server /data
    volumes:
      - minio_data:/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: clothes_app
    depends_on:
      - postgres
      - redis
      - minio
    ports:
      - 5000:5000
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:5000

volumes:
  postgres_data:
  redis_data:
  minio_data:
